"""Initial schema

Revision ID: dd178888e641
Revises: 
Create Date: 2026-01-20 07:32:44.078764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd178888e641'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercise_library',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('normalized_name', sa.String(), nullable=False),
    sa.Column('primary_muscle_group', sa.String(), nullable=False),
    sa.Column('equipment', sa.String(), nullable=False),
    sa.Column('movement_type', sa.String(), nullable=False),
    sa.Column('aliases', sa.ARRAY(sa.String()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('variation_of', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['variation_of'], ['exercise_library.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercise_library_name'), 'exercise_library', ['name'], unique=False)
    op.create_index(op.f('ix_exercise_library_normalized_name'), 'exercise_library', ['normalized_name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('units', sa.String(), nullable=False),
    sa.Column('timezone', sa.String(), nullable=False),
    sa.Column('default_rest_timer_seconds', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('workouts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('lifecycle_status', sa.String(), nullable=False),
    sa.Column('completion_status', sa.String(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_workouts_user_completion', 'workouts', ['user_id', 'completion_status', sa.text('start_time DESC')], unique=False)
    op.create_index('idx_workouts_user_start', 'workouts', ['user_id', sa.text('start_time DESC')], unique=False)
    op.create_index(op.f('ix_workouts_user_id'), 'workouts', ['user_id'], unique=False)
    op.create_table('daily_training_state',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('worked_out', sa.Boolean(), nullable=False),
    sa.Column('workout_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workout_id'], ['workouts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='unique_user_date')
    )
    op.create_index(op.f('ix_daily_training_state_user_id'), 'daily_training_state', ['user_id'], unique=False)
    op.create_table('workout_exercises',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workout_id', sa.UUID(), nullable=False),
    sa.Column('exercise_id', sa.UUID(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise_library.id'], ),
    sa.ForeignKeyConstraint(['workout_id'], ['workouts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_workout_exercises_workout_order', 'workout_exercises', ['workout_id', 'order_index'], unique=False)
    op.create_table('workout_sets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workout_exercise_id', sa.UUID(), nullable=False),
    sa.Column('set_number', sa.Integer(), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('rpe', sa.String(), nullable=True),
    sa.Column('set_type', sa.String(), nullable=False),
    sa.Column('rest_time_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workout_exercise_id'], ['workout_exercises.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_workout_sets_exercise_set', 'workout_sets', ['workout_exercise_id', 'set_number'], unique=False)
    
    # Add partial unique index for active drafts (LOCKED)
    op.execute("""
        CREATE UNIQUE INDEX unique_active_draft_per_user 
        ON workouts(user_id) 
        WHERE lifecycle_status = 'draft';
    """)
    
    # Add pg_trgm extension for exercise search
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm;")
    
    # Add exercise search indexes
    op.execute("""
        CREATE INDEX idx_exercise_name_trgm 
        ON exercise_library 
        USING gin(name gin_trgm_ops);
    """)
    
    op.execute("""
        CREATE INDEX idx_exercise_aliases_gin 
        ON exercise_library 
        USING gin(aliases);
    """)
    
    op.execute("""
        CREATE INDEX idx_exercise_normalized_name 
        ON exercise_library(normalized_name);
    """)
    
    # Note: Unique index on normalized_name alone was created here initially,
    # but was later changed to (normalized_name, equipment) in migration a1b2c3d4e5f6
    # to allow same exercise name with different equipment (e.g., "Shrugs" barbell vs dumbbell)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop custom indexes
    # Note: uq_exercise_normalized_name was replaced by uq_exercise_unique in later migration
    op.execute("DROP INDEX IF EXISTS uq_exercise_unique;")
    op.execute("DROP INDEX IF EXISTS uq_exercise_normalized_name;")
    op.execute("DROP INDEX IF EXISTS idx_exercise_normalized_name;")
    op.execute("DROP INDEX IF EXISTS idx_exercise_aliases_gin;")
    op.execute("DROP INDEX IF EXISTS idx_exercise_name_trgm;")
    op.execute("DROP EXTENSION IF EXISTS pg_trgm;")
    op.execute("DROP INDEX IF EXISTS unique_active_draft_per_user;")
    
    op.drop_index('idx_workout_sets_exercise_set', table_name='workout_sets')
    op.drop_table('workout_sets')
    op.drop_index('idx_workout_exercises_workout_order', table_name='workout_exercises')
    op.drop_table('workout_exercises')
    op.drop_index(op.f('ix_daily_training_state_user_id'), table_name='daily_training_state')
    op.drop_table('daily_training_state')
    op.drop_index(op.f('ix_workouts_user_id'), table_name='workouts')
    op.drop_index('idx_workouts_user_start', table_name='workouts')
    op.drop_index('idx_workouts_user_completion', table_name='workouts')
    op.drop_table('workouts')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_exercise_library_normalized_name'), table_name='exercise_library')
    op.drop_index(op.f('ix_exercise_library_name'), table_name='exercise_library')
    op.drop_table('exercise_library')
    # ### end Alembic commands ###
